apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rafiki-backend.fullname" . }}-secrets
  labels:
{{ include "rafiki-backend.labels" . | indent 4 }}
data:
  DATABASE_URL: {{ include "backend.postgresqlUrl" . | b64enc | quote }}
  REDIS_URL: {{ include "backend.redisUrl" . | b64enc | quote }}
  SIGNATURE_SECRET: "{{ .Values.quoteSignatureSecret | b64enc }}"
  STREAM_SECRET: "{{ .Values.ilp.streamSecret | b64enc }}"
