{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "backend.serviceAccountName" . }}
  labels:
{{ include "rafiki-backend.labels" . | indent 4 }}
{{- end -}}
