apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rafiki-auth.fullname" . }}-secrets
  labels:
{{ include "rafiki-auth.labels" . | indent 4 }}
data:
  AUTH_DATABASE_URL: {{ include "auth.postgresqlUrl" . | b64enc | quote }}
  COOKIE_KEY: "{{ .Values.cookieKey | b64enc }}"
  IDENTITY_SERVER_SECRET: "{{ .Values.identityServer.secret | b64enc }}"