{{- include "common.secret" (list . "rafiki-auth.secret") }}
{{- define "rafiki-auth.secret" -}}
{{- $top := first . }}
data:
  {{- range $top.Values.secrets }}
    {{- tpl ($top.Files.Get .) $top | nindent 6 -}}
  {{- end }}
{{- end }}