apiVersion: v1
kind: Service
metadata:
  name: {{ include "rafiki-auth.fullname" . }}
  labels:
    app: {{ include "rafiki-auth.name" . }}
    chart: {{ include "rafiki-auth.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port.auth }}
      targetPort: {{ .Values.port.auth }}
      protocol: TCP
      name: auth
    - port: {{ .Values.port.admin }}
      targetPort: {{ .Values.port.admin }}
      protocol: TCP
      name: admin
    - port: {{ .Values.port.introspection }}
      targetPort: {{ .Values.port.introspection }}
      protocol: TCP
      name: introspection
  selector:
    app.kubernetes.io/name: {{ include "rafiki-auth.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
