DATABASE_URL: {{ (printf "postgresql://%s:%s@%s:%s/%s" .Values.postgresql.username .Values.postgresql.password .Values.postgresql.host .Values.postgresql.port .Values.postgresql.database) | b64enc | quote }}
REDIS_URL: {{ (printf "redis://%s:%s" .Values.redis.host .Values.redis.port) | b64enc | quote }}
SIGNATURE_SECRET: "{{ .Values.quoteSignatureSecret | b64enc }}"
STREAM_SECRET: "{{ .Values.ilp.streamSecret | b64enc }}"