apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rafiki-frontend.fullname" . }}
  labels: 
{{ include "rafiki-frontend.labels" . | indent 4 }}
data: 
  GRAPHQL_URL: "{{ .Values.serviceUrls.GRAPHQL_URL}}"
  LOG_LEVEL: debug
  NODE_ENV: "{{ .Values.nodeEnv }}"
  PORT: "{{ .Values.port }}"
  KRATOS_CONTAINER_PUBLIC_URL: "{{ .Values.kratos.containerPublicUrl }}"
  KRATOS_BROWSER_PUBLIC_URL: "{{ .Values.kratos.browserPublicUrl }}"
  KRATOS_ADMIN_URL: "{{ .Values.kratos.adminUrl }}"
