apiVersion: v1
kind: Service
metadata:
  name: {{ include "rafiki-frontend.fullname" . }}
  labels:
    app: {{ include "rafiki-frontend.name" . }}
    chart: {{ include "rafiki-frontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "rafiki-frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
