ACCESS_TOKEN_DELETION_DAYS: "{{ .Values.accessToken.deletionDays }}"
ACCESS_TOKEN_EXPIRY_SECONDS: "{{ .Values.accessToken.expirySeconds }}"
ADMIN_PORT: "{{ .Values.port.admin }}"
AUTH_PORT: "{{ .Values.port.auth }}"
DATABASE_CLEANUP_WORKERS: "{{ .Values.workers.cleanup }}"
IDENTITY_SERVER_DOMAIN: "{{ .Values.identityServer.domain }}"
INCOMING_PAYMENT_INTERACTION: "{{ .Values.interaction.incomingPayment }}"
QUOTE_INTERACTION: "{{ .Values.interaction.quote }}"
INTROSPECTION_PORT: "{{ .Values.port.introspection }}"
LOG_LEVEL: "{{ .Values.logLevel }}"
NODE_ENV: "{{ .Values.nodeEnv }}"
PORT: "{{ .Values.port.auth }}"
WAIT_SECONDS: "{{ .Values.grant.waitSeconds }}"