AUTH_DATABASE_URL: {{ (printf "postgresql://%s:%s@%s:%s/%s" .Values.postgresql.username .Values.postgresql.password .Values.postgresql.host .Values.postgresql.port .Values.postgresql.database) | b64enc | quote }}
COOKIE_KEY: "{{ .Values.cookieKey | b64enc }}"
IDENTITY_SERVER_SECRET: "{{ .Values.identityServer.secret | b64enc }}"